server:
  port: 9090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_nexon?useUnicode=true&amp;characterEncoding=UTF-8
    username: qlchat
    password: 7dRa0Khh
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 3000
      pool-prepared-statements: false
      max-open-prepared-statements: -1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 40000
      filters: stat,wall
      aop-patterns: com.nexon.dao.*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
        allow: 127.0.0.1
        deny:
application:
  wechat:
    token: naxon
    aesKey: uDtsDjE5Ddx2idzNBMTKNQ8e9tn45JM21whwmwSNaXe
    ghId: gh_bd74d9636d92
    appId: wxa130f378f17b1626
    appSecret: cdb6c99e07c06a635affa476bd962a7d