package com.nexon.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class BiliUserFollower implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bili_user_follower.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bili_user_follower.mid
     *
     * @mbg.generated
     */
    private Long mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bili_user_follower.following
     *
     * @mbg.generated
     */
    private Long following;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bili_user_follower.whisper
     *
     * @mbg.generated
     */
    private Long whisper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bili_user_follower.black
     *
     * @mbg.generated
     */
    private Long black;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bili_user_follower.follower
     *
     * @mbg.generated
     */
    private Long follower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bili_user_follower.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bili_user_follower.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bili_user_follower
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bili_user_follower.id
     *
     * @return the value of bili_user_follower.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bili_user_follower.id
     *
     * @param id the value for bili_user_follower.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bili_user_follower.mid
     *
     * @return the value of bili_user_follower.mid
     *
     * @mbg.generated
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bili_user_follower.mid
     *
     * @param mid the value for bili_user_follower.mid
     *
     * @mbg.generated
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bili_user_follower.following
     *
     * @return the value of bili_user_follower.following
     *
     * @mbg.generated
     */
    public Long getFollowing() {
        return following;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bili_user_follower.following
     *
     * @param following the value for bili_user_follower.following
     *
     * @mbg.generated
     */
    public void setFollowing(Long following) {
        this.following = following;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bili_user_follower.whisper
     *
     * @return the value of bili_user_follower.whisper
     *
     * @mbg.generated
     */
    public Long getWhisper() {
        return whisper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bili_user_follower.whisper
     *
     * @param whisper the value for bili_user_follower.whisper
     *
     * @mbg.generated
     */
    public void setWhisper(Long whisper) {
        this.whisper = whisper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bili_user_follower.black
     *
     * @return the value of bili_user_follower.black
     *
     * @mbg.generated
     */
    public Long getBlack() {
        return black;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bili_user_follower.black
     *
     * @param black the value for bili_user_follower.black
     *
     * @mbg.generated
     */
    public void setBlack(Long black) {
        this.black = black;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bili_user_follower.follower
     *
     * @return the value of bili_user_follower.follower
     *
     * @mbg.generated
     */
    public Long getFollower() {
        return follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bili_user_follower.follower
     *
     * @param follower the value for bili_user_follower.follower
     *
     * @mbg.generated
     */
    public void setFollower(Long follower) {
        this.follower = follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bili_user_follower.gmt_create
     *
     * @return the value of bili_user_follower.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bili_user_follower.gmt_create
     *
     * @param gmtCreate the value for bili_user_follower.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bili_user_follower.gmt_modified
     *
     * @return the value of bili_user_follower.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bili_user_follower.gmt_modified
     *
     * @param gmtModified the value for bili_user_follower.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili_user_follower
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mid=").append(mid);
        sb.append(", following=").append(following);
        sb.append(", whisper=").append(whisper);
        sb.append(", black=").append(black);
        sb.append(", follower=").append(follower);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}