package com.nexon.dao.mapper;

import com.nexon.dao.entity.WechatAppConfig;
import java.util.List;

public interface WechatAppConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_app_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_app_config
     *
     * @mbg.generated
     */
    int insert(WechatAppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_app_config
     *
     * @mbg.generated
     */
    WechatAppConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_app_config
     *
     * @mbg.generated
     */
    List<WechatAppConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_app_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WechatAppConfig record);
}