package com.nexon.dao.mapper;

import com.nexon.dao.entity.WechatUserInfo;
import java.util.List;

public interface WechatUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user_info
     *
     * @mbg.generated
     */
    int insert(WechatUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user_info
     *
     * @mbg.generated
     */
    WechatUserInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user_info
     *
     * @mbg.generated
     */
    List<WechatUserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WechatUserInfo record);
}