package com.naxon.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class WechatUserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.unionid
     *
     * @mbg.generated
     */
    private String unionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.subscribe
     *
     * @mbg.generated
     */
    private Integer subscribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.language
     *
     * @mbg.generated
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.headimgurl
     *
     * @mbg.generated
     */
    private String headimgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.subscribe_time
     *
     * @mbg.generated
     */
    private Date subscribeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.groupid
     *
     * @mbg.generated
     */
    private Integer groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.tagid_list
     *
     * @mbg.generated
     */
    private String tagidList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.subscribe_scene
     *
     * @mbg.generated
     */
    private String subscribeScene;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.qr_scene
     *
     * @mbg.generated
     */
    private String qrScene;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.qr_scene_str
     *
     * @mbg.generated
     */
    private String qrSceneStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_user_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.id
     *
     * @return the value of wechat_user_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.id
     *
     * @param id the value for wechat_user_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.app_id
     *
     * @return the value of wechat_user_info.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.app_id
     *
     * @param appId the value for wechat_user_info.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.openid
     *
     * @return the value of wechat_user_info.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.openid
     *
     * @param openid the value for wechat_user_info.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.unionid
     *
     * @return the value of wechat_user_info.unionid
     *
     * @mbg.generated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.unionid
     *
     * @param unionid the value for wechat_user_info.unionid
     *
     * @mbg.generated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.subscribe
     *
     * @return the value of wechat_user_info.subscribe
     *
     * @mbg.generated
     */
    public Integer getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.subscribe
     *
     * @param subscribe the value for wechat_user_info.subscribe
     *
     * @mbg.generated
     */
    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.nickname
     *
     * @return the value of wechat_user_info.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.nickname
     *
     * @param nickname the value for wechat_user_info.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.sex
     *
     * @return the value of wechat_user_info.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.sex
     *
     * @param sex the value for wechat_user_info.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.language
     *
     * @return the value of wechat_user_info.language
     *
     * @mbg.generated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.language
     *
     * @param language the value for wechat_user_info.language
     *
     * @mbg.generated
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.city
     *
     * @return the value of wechat_user_info.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.city
     *
     * @param city the value for wechat_user_info.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.province
     *
     * @return the value of wechat_user_info.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.province
     *
     * @param province the value for wechat_user_info.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.country
     *
     * @return the value of wechat_user_info.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.country
     *
     * @param country the value for wechat_user_info.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.headimgurl
     *
     * @return the value of wechat_user_info.headimgurl
     *
     * @mbg.generated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.headimgurl
     *
     * @param headimgurl the value for wechat_user_info.headimgurl
     *
     * @mbg.generated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.subscribe_time
     *
     * @return the value of wechat_user_info.subscribe_time
     *
     * @mbg.generated
     */
    public Date getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.subscribe_time
     *
     * @param subscribeTime the value for wechat_user_info.subscribe_time
     *
     * @mbg.generated
     */
    public void setSubscribeTime(Date subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.remark
     *
     * @return the value of wechat_user_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.remark
     *
     * @param remark the value for wechat_user_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.groupid
     *
     * @return the value of wechat_user_info.groupid
     *
     * @mbg.generated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.groupid
     *
     * @param groupid the value for wechat_user_info.groupid
     *
     * @mbg.generated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.tagid_list
     *
     * @return the value of wechat_user_info.tagid_list
     *
     * @mbg.generated
     */
    public String getTagidList() {
        return tagidList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.tagid_list
     *
     * @param tagidList the value for wechat_user_info.tagid_list
     *
     * @mbg.generated
     */
    public void setTagidList(String tagidList) {
        this.tagidList = tagidList == null ? null : tagidList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.subscribe_scene
     *
     * @return the value of wechat_user_info.subscribe_scene
     *
     * @mbg.generated
     */
    public String getSubscribeScene() {
        return subscribeScene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.subscribe_scene
     *
     * @param subscribeScene the value for wechat_user_info.subscribe_scene
     *
     * @mbg.generated
     */
    public void setSubscribeScene(String subscribeScene) {
        this.subscribeScene = subscribeScene == null ? null : subscribeScene.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.qr_scene
     *
     * @return the value of wechat_user_info.qr_scene
     *
     * @mbg.generated
     */
    public String getQrScene() {
        return qrScene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.qr_scene
     *
     * @param qrScene the value for wechat_user_info.qr_scene
     *
     * @mbg.generated
     */
    public void setQrScene(String qrScene) {
        this.qrScene = qrScene == null ? null : qrScene.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.qr_scene_str
     *
     * @return the value of wechat_user_info.qr_scene_str
     *
     * @mbg.generated
     */
    public String getQrSceneStr() {
        return qrSceneStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.qr_scene_str
     *
     * @param qrSceneStr the value for wechat_user_info.qr_scene_str
     *
     * @mbg.generated
     */
    public void setQrSceneStr(String qrSceneStr) {
        this.qrSceneStr = qrSceneStr == null ? null : qrSceneStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.gmt_create
     *
     * @return the value of wechat_user_info.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.gmt_create
     *
     * @param gmtCreate the value for wechat_user_info.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info.gmt_modified
     *
     * @return the value of wechat_user_info.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info.gmt_modified
     *
     * @param gmtModified the value for wechat_user_info.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", openid=").append(openid);
        sb.append(", unionid=").append(unionid);
        sb.append(", subscribe=").append(subscribe);
        sb.append(", nickname=").append(nickname);
        sb.append(", sex=").append(sex);
        sb.append(", language=").append(language);
        sb.append(", city=").append(city);
        sb.append(", province=").append(province);
        sb.append(", country=").append(country);
        sb.append(", headimgurl=").append(headimgurl);
        sb.append(", subscribeTime=").append(subscribeTime);
        sb.append(", remark=").append(remark);
        sb.append(", groupid=").append(groupid);
        sb.append(", tagidList=").append(tagidList);
        sb.append(", subscribeScene=").append(subscribeScene);
        sb.append(", qrScene=").append(qrScene);
        sb.append(", qrSceneStr=").append(qrSceneStr);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}